### ISSUE TITLE
运行代码

### ISSUE THREAD

**Issue by geasyheart** [AAIG-NLP/UniIE#1]
作者大大好，感谢开源项目，能提供一个完整的运行代码吗？
还有一个问题，如果多论元共用同一触发词，怎么建模？
甚至还可以说，如果也不依赖触发词，就要将句子里面所有事件都进行抽取，有什么好的办法推荐吗？

非常感谢╰(*´︶`*)╯

**Comment by yyht** [comment]
Run.sh训练，predict.sh是预测（ccks22）
基本原理参考 paperweekly的文章即可


是否有无触发词，是否多伦元共享触发词都可以的，输出是 同一个句子里面 同一个类型的所有元组，通过 组 分隔符区分（预处理里面都有）



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月22日(周四) 晚上9:26
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [AAIG-NLP/UniIE] 运行代码 (Issue #1)




 
作者大大好，感谢开源项目，能提供一个完整的运行代码吗？
 还有一个问题，如果多论元共用同一触发词，怎么建模？
 甚至还可以说，如果也不依赖触发词，就要将句子里面所有事件都进行抽取，有什么好的办法推荐吗？
 
非常感谢╰(´︶`)╯
